#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    tecweb04api-app:
        image: tecweb04api
        external_links:
            - tecweb04api-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - tecweb04api-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tecweb04api?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    tecweb04api-mysql:
        extends:
            file: mysql.yml
            service: tecweb04api-mysql
    # Uncomment to have Cassandra working with the gateway
    # tecweb04api-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: tecweb04api-cassandra
    # tecweb04api-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: tecweb04api-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
